name: pre-commit
description: Wrapper for running pre-commit image that runs as a non root user
author: batinicaz

inputs:
  image:
    description: The pre-commit image to use
    default: ghcr.io/batinicaz/pre-commit:latest
    required: false
  path:
    description: The path to the configuration to run pre-commit against
    default: ${{ github.workspace }}
    required: false

runs:
  using: composite
  steps:
    - name: Cache pre-commit environments
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # ratchet:actions/cache@v5
      with:
        path: ${{ runner.temp }}/pre-commit-cache
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-

    - name: Run pre-commit
      run: |
        mkdir -p "${{ runner.temp }}/pre-commit-cache"
        sudo chown -R 65532 "${{ inputs.path }}" "${{ runner.temp }}/pre-commit-cache"
        docker run --rm -w /test \
          -v "${{ inputs.path }}":/test \
          -v "${{ runner.temp }}/pre-commit-cache":/pre-commit-cache \
          -e PRE_COMMIT_HOME=/pre-commit-cache \
          ${{ inputs.image }}
        sudo chown -R $(id -u):$(id -g) "${{ inputs.path }}" "${{ runner.temp }}/pre-commit-cache"
      shell: bash
