# Auto release this repo on merge to main
name: Create Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      includeLatestTag: true
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_INSTALL_ID: ${{ secrets.APP_INSTALL_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
