# Auto release this repo on merge to main
name: Create Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      includeLatestTag: true
    secrets: inherit
